apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome
  labels:
    app: welcome
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
      - image: okteto/welcome:0.1.1
        imagePullPolicy: Always
        name: web1
        ports:
        - containerPort: 8080
      - image: okteto/welcome:0.1.2
        imagePullPolicy: Always
        name: web2
        ports:
        - containerPort: 8081      